
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:elasticsearch
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: {{ .Values.elasticSearchHost | quote }}
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: {{ .Values.elasticSearchPort | quote }}
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: {{ .Values.elasticScheme | quote }}
          # X-Pack Authentication
          # =====================
          - name: FLUENT_ELASTICSEARCH_USER
            value: {{ .Values.fluentDUsername }}
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretsRef | quote }}
                key: {{ .Values.fluentDPasswordKey }}
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory | quote }}
          requests:
            memory: {{ .Values.resources.requests.memory | quote }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varcontainers
          mountPath: /var/log/containers/
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varcontainers
        hostPath:
          path: /var/log/containers/