# Basic info
replicaCount: 3
secretsRef: "__REQUIRED__"
image:
  repository: 
  tag: 
  pullPolicy: Always

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi
javaHeap: 256M

# Monitoring
monitoring:
  pipeline: "__REQUIRED__"
  enabled: true
  port: 9102
  path: "/metrics"

#Schema registry configuration
rest: 
  zookeeperConnect: zookeeper:2181
  schemaRegistryUrl: schema-registry:8081  
  listeners: http://0.0.0.0:8082
  debug: false
  restPort: 8082
