kind: ConfigMap
metadata:
  name: "{{ include "fullname" . }}"
  labels:
    app: "{{ include "fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{- if and .Values.lenses.kafka.sasl.enabled (eq .Values.lenses.kafka.sasl.mechanism "GSSAPI") }}
  krb5.conf:
{{ .Values.lenses.kafka.sasl.krb5Conf | indent 4 }}
{{- end }}