apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        hostPort: {{ .Values.restPort | quote }}
        containerPort: {{ .Values.restPort | quote }}
        pipeline: {{ .Values.monitoring.pipeline | quote }}
      annotations:
        prometheus.io/scrape: {{ .Values.monitoring.enabled | quote }}
        prometheus.io/port: {{ .Values.monitoring.port | quote }}
        prometheus.io/path: {{ .Values.monitoring.path | quote }}
    spec:
      volumes:
        - name: lenses-secrets
          secret:
            secretName: {{ template "fullname" . }}
            defaultMode: 256
            items:
              - key: secrets
                path: LENSES_SECURITY
              - key: license 
                path: license.json   
        - name: lenses-settings
          configMap:
            name: {{ template "fullname" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.restPort }}
        livenessProbe:
          exec:
            command:
            - /etc/landoop/liveliness.sh
          initialDelaySeconds: 30
          timeoutSeconds: 5
        volumeMounts:
          - name: lenses-settings
            mountPath: "/mnt/settings"
          - name: lenses-secrets
            mountPath: "/mnt/secrets"
            readOnly: true
        env:
          - name: LENSES_HEAP_OPTS
            value: {{ .Values.lensesOpts | quote }}   
        resources:
{{ toYaml .Values.resources | indent 10 }}
