apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "fullname" . | quote }}
  labels:
    app: {{ include "fullname" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: "lenses"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "fullname" . | quote }}
        component: "lenses"
        hostPort: {{ .Values.restPort | quote }}
        containerPort: {{ .Values.restPort | quote }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        prometheus.io/path: "/metrics"
    spec:
      volumes:  
        {{- if or .Values.lenses.kafka.ssl.enabled .Values.lenses.kafka.sasl.enabled }}              
        - name: secrets
          secret:
            secretName: {{ include "fullname" . | quote }}
            items:
              {{- if .Values.lenses.kafka.ssl.enabled }}
              - key: client.keystore.jks
                path: client.keystore.jks
              - key: client.truststore.jks 
                path: client.truststore.jks
              {{- end }}  
              {{- if .Values.lenses.kafka.sasl.enabled }}
              - key: jaas.conf
                path: jaas.conf
              - key: keytab
                path: keytab  
              {{- end }}
        {{- end }}  
        {{- if and .Values.lenses.kafka.sasl.enabled (eq .Values.lenses.kafka.sasl.mechanism "GSSAPI") }}
        - name: krb
          configMap:
            name: {{ include "fullname" . | quote }}
        {{- end }}  
      serviceAccountName: {{ .Values.serviceAccount }}      
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.restPort }}
        livenessProbe:
          httpGet:
            path: /
            port: 3030
          initialDelaySeconds: 120
          periodSeconds: 3
        volumeMounts:
          {{- if or .Values.lenses.kafka.ssl.enabled .Values.lenses.kafka.sasl.enabled }} 
          - name: secrets
            mountPath: "/mnt/secrets"
          {{- end }} 
          {{- if and .Values.lenses.kafka.sasl.enabled (eq .Values.lenses.kafka.sasl.mechanism "GSSAPI") }}
          - name: krb
            mountPath: "/etc/krb5.conf"
            subPath: "krb5.conf"
          {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}     
        env:
        {{- if .Values.lenses.licenseUrl }} 
        - name: LICENSE_URL
          value:
        {{- end }}
        {{- if .Values.lenses.kafka.sasl.enabled }}
        - name: LENSES_OPTS
          value: "-Djava.security.auth.login.config=/mnt/secrets/jaas.conf"
        {{- end }}
        {{- if.Values.lenses.jvm.heapOpts}}
        - name: LENSES_HEAP_OPTS
          value: {{ .Values.lenses.jvm.heapOpts | quote }}
        {{- end }}  
        {{- if.Values.lenses.jvm.logBackOpts}}
        - name: LENSES_LOG4J_OPTS
          value: {{ .Values.lenses.jvm.logBackOpts | quote }}
        {{- end }} 
        {{- if.Values.lenses.jvm.performanceOpts}}
        - name: LENSES_PERFORMANCE_OPTS
          value: {{ .Values.lenses.jvm.performanceOpts | quote }}
        {{- end }} 
        {{- if .Values.ingress.enabled }}
        - name: LENSES_ROOT_PATH
          value: {{ include "ingressPath" . | quote }}
        {{- end }}
        - name: LICENSE
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key: "license"   
        - name: LENSES_KUBERNETES_IMAGE_NAME
          value: {{ .Values.lenses.sql.processorImage | quote }}
        - name: LENSES_KUBERNETES_IMAGE_TAG
          value: {{ .Values.lenses.sql.processorImageTag | quote }}
        - name: LENSES_KUBERNETES_SERVICE_ACCOUNT
          value: {{ .Values.serviceAccount | quote }}
        - name: LENSES_SQL_EXECUTION_MODE
          value: "KUBERNETES"        
        - name: LENSES_KUBERNETES_CONFIG_FILE
          value: '""'
        - name: LENSES_PORT
          value: {{ .Values.restPort | quote }}
        - name: LENSES_JMX_PORT
          value: "9101"
        - name: LENSES_KAFKA_BROKERS
          value: {{ include "bootstrapBrokers" . | quote }}
        - name: LENSES_ZOOKEEPER_HOSTS
          value: |-
{{ include "zookeepers" . | indent 12 }}
        - name: LENSES_SCHEMA_REGISTRY_URLS
          value: |-
{{ include "registries" . | indent 12 }}
        - name: LENSES_CONNECT_CLUSTERS
          value: |-
{{ include "connect" . | indent 12 }}         
        - name: LENSES_ALERT_MANAGER_ENDPOINTS
          value: {{ include "alertManagers" . | quote }}  
        - name: LENSES_ALERT_MANAGER_SOURCE
          value: "{{ .Values.lenses.alertManagers.sourceName }}-{{ include "fullname" .}}-{{ .Release.Namespace }}"
        - name: LENSES_ALERT_CONSUMERS_LAG_THRESHOLD
          value: {{ .Values.lenses.alertManagers.consumersLagThreshold | quote }}
        - name: LENSES_ALERT_SLACK_ENABLED
          value: {{ .Values.lenses.slack.enabled | quote }}
        {{- if .Values.lenses.slack.enabled }}                            
        - name: LENSES_ALERT_SLACK_WEBHOOK_URL
          value: {{ .Values.lenses.slack.webhookUrl | quote }}
        - name: LENSES_ALERT_SLACK_ICON_URL
          value: "https://www.landoop.com/images/landoop-dark.svg"
        - name: LENSES_ALERT_SLACK_USERNAME
          value: {{ .Values.lenses.slack.username | quote }}
        - name: LENSES_ALERT_SLACK_CHANNEL
          value: {{ .Values.lenses.slack.channel | quote }}
        {{- end }}  
        - name: LENSES_GRAFANA
          value: {{ .Values.lenses.grafanaUrl | quote }}      
        - name: LENSES_TOPICS_PROCESSORS
          value: {{ include "processorTopic" . | quote }}                          
        - name: LENSES_TOPICS_ALERTS
          value: {{ include "alertTopic" . | quote }}
        - name: LENSES_TOPICS_AUDITS
          value: {{ include "auditTopic" . | quote }}
        - name: LENSES_TOPICS_METRICS
          value: {{ include "metricTopic" . | quote }}
        - name: LENSES_TOPICS_PROFILES
          value: {{ include "profileTopic" . | quote }}
        - name: LENSES_TOPICS_ALERTS_STORAGE
          value: {{ include "alertSettingTopic" . | quote }}
        - name: LENSES_TOPICS_CLUSTER
          value: {{ include "clusterTopic" . | quote }}  
        - name: LENSES_TOPICS_LSQL_STORAGE
          value: {{ include "lsqlTopic" . | quote }}             

        # security
        - name: LENSES_SECURITY_MODE
          value: {{ .Values.lenses.security.mode }} 

        {{- if .Values.lenses.security.groups }}    
        - name: LENSES_SECURITY_GROUPS
          value: |-
{{ include "userGroups" . | indent 12 }} 
        {{- end -}} 

        {{- if .Values.lenses.security.users }}                  
        - name: LENSES_SECURITY_USERS  
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key: "users" 
        {{- end -}}  

        {{- if .Values.lenses.security.serviceAccount }}                  
        - name: LENSES_SECURITY_SERVICE_ACCOUNTS 
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key: "serviceAccounts" 
        {{- end -}}                
        
        {{- if eq .Values.lenses.security.mode "LDAP" }}
        #ldap
        - name: LENSES_SECURITY_LDAP_URL
          value: {{ .Values.lenses.security.ldap.url }}
        - name: LENSES_SECURITY_LDAP_BASE
          value: {{ .Values.lenses.security.ldap.base }}
        - name: LENSES_SECURITY_LDAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "ldap.password"
        - name: LENSES_SECURITY_LDAP_USER
          value: {{ .Values.lenses.security.ldap.user }}
        - name: LENSES_SECURITY_LDAP_FILTER
          value: {{ .Values.lenses.security.ldap.filter }}
        - name: LENSES_SECURITY_LDAP_PLUGIN_CLASS
          value: {{ .Values.lenses.security.ldap.plugin.class }}
        - name: LENSES_SECURITY_LDAP_PLUGIN_MEMBEROF_KEY
          value: {{ .Values.lenses.security.ldap.plugin.memberofKey }}
        - name: LENSES_SECURITY_LDAP_PLUGIN_GROUP_EXTRACT_REGEX
          value: {{ .Values.lenses.security.ldap.plugin.groupExtractRegex }} 
        - name: LENSES_SECURITY_LDAP_PLUGIN_PERSON_NAME_KEY
          value: {{ .Values.lenses.security.ldap.plugin.personNameKey }}                           
        {{- end }} 

        - name: LENSES_KAFKA_SETTINGS_CONSUMER_SECURITY_PROTOCOL
          value: {{ include "securityProtocol" . | quote }}
        - name: LENSES_KAFKA_SETTINGS_PRODUCER_SECURITY_PROTOCOL
          value: {{ include "securityProtocol" . | quote }}  

        {{- if .Values.lenses.kafka.sasl.enabled }}
        - name: LENSES_KAFKA_SETTINGS_CONSUMER_SASL_MECHANISM
          value: {{ default "GSSAPI" .Values.lenses.kafka.sasl.mechanism | quote }}    
        - name: LENSES_KAFKA_SETTINGS_PRODUCER_SASL_MECHANISM
          value: {{ default "GSSAPI" .Values.lenses.kafka.sasl.mechanism | quote }}    
        {{- end }}  
   
        {{- if .Values.lenses.kafka.ssl.enabled }}
        - name: LENSES_KAFKA_SETTINGS_CONSUMER_SSL_TRUSTSTORE_LOCATION
          value: "/mnt/secrets/client.truststore.jks"
        - name: LENSES_KAFKA_SETTINGS_CONSUMER_SSL_KEYSTORE_LOCATION
          value: "/mnt/secrets/client.keystore.jks"
        - name: LENSES_KAFKA_SETTINGS_CONSUMER_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "client.truststore.password"                  
        - name: LENSES_KAFKA_SETTINGS_CONSUMER_SSL_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "client.keystore.password"
        - name: LENSES_KAFKA_SETTINGS_CONSUMER_SSL_KEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "client.key.password"      

        - name: LENSES_KAFKA_SETTINGS_PRODUCER_SSL_TRUSTSTORE_LOCATION
          value: "/mnt/secrets/client.truststore.jks"
        - name: LENSES_KAFKA_SETTINGS_PRODUCER_SSL_KEYSTORE_LOCATION
          value: "/mnt/secrets/client.keystore.jks"
        - name: LENSES_KAFKA_SETTINGS_PRODUCER_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "client.truststore.password"                  
        - name: LENSES_KAFKA_SETTINGS_PRODUCER_SSL_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "client.keystore.password"
        - name: LENSES_KAFKA_SETTINGS_PRODUCER_SSL_KEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "client.key.password"                              
        {{- end }}

        {{- range $key, $value := .Values.configOverrides }}
        - name: {{ printf "%s" $key | replace "." "_" | upper | quote }}
          value: {{ $value | quote }}
        {{- end }}