{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "fullname" . }}-ingress"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: {{ .Release.Service }}
data:
  tls.crt: |-
{{ .Values.ingress.tls.crt | indent 4 }}
  tls.key: |-
{{ .Values.ingress.tls.key | indent 4 }}
{{- end -}}
{{- end -}}