apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
  annotations:
    "helm.sh/hook": pre-install
data:
  license: |-
{{ .Files.Get .Values.licenseFile | b64enc | indent 2 }}
  secrets: |-
{{ .Files.Get .Values.securityFile | b64enc | indent 2 }}