kind: Secret
apiVersion: v1
metadata:
  name: {{ include "fullname" . }}
  labels:
    app: {{ include "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    lenses: lenses-secret
data:
  {{- if .Values.lenses.kafka.ssl.enabled }}
  client.truststore.jks: {{ .Values.lenses.kafka.ssl.trustStoreFileData }}
  client.keystore.jks: {{ .Values.lenses.kafka.ssl.keyStoreFileData }}
  {{- end }}
stringData:
  security.conf: |-
{{ include "securityConf" . | indent 4 }}
  license: {{ .Values.lenses.license | quote }}
  {{- if .Values.lenses.kafka.sasl.enabled }}
  jaas.conf: |-
{{ .Values.lenses.kafka.sasl.jaasFileData | default "" | indent 4 }}
  keytab: |-  
{{ .Values.lenses.kafka.sasl.keyTabData | default "" | indent 4 }}
  {{- end }}
  {{- if eq .Values.lenses.security.mode "KERBEROS" }} 
  lenses.keytab:
{{ .Values.lenses.security.kerberos.keytabData | indent 4 }}
  {{- end -}}
