# Basic info
replicaCount: 1
# secretsRef The secret holding any passwords
secretsRef: "__REQUIRED__"
image:
  repository: registry.hub.docker.com/landoop/lenses
  tag: 0.4.1
  pullPolicy: IfNotPresent

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi

# lensesOpts options Set any jvm options
lensesJVMOpts: 256M

# Monitoring
monitoring:
  pipeline: "__REQUIRED__"
  enabled: true
  port: 3030
  path: "/metrics"

# restPort is the Lenses rest port
restPort: 3030

# configFile is the Lenses config file to create a configmap
configFile: "__REQUIRED__"

# securityFile is the file containg Lenses secrets (usernames/passwords) mounted as secret LENSES_SECRUITY in /mnt/secrets
securityFile: "__REQUIRED__"

# licenseFile is the file containing the Lenses license key mounted as license.json in /mnt/secrets
licenseFile: "__REQUIRED__"