# Basic info
secretsRef: "__REQUIRED__"
image:
  repository: fluent/fluentd-kubernetes-daemonset:elasticsearch
  tag: stable
  pullPolicy: Always

namespace: de-datahub-d

# elasticScheme http or http
elasticScheme: http
# elasticSearch host
elasticSearchHost: elastic
# elasticSearch port
elasticSearchPort: 9200  
# elasticUsername
fluentDUsername: fluentd
# password keys
fluentDPasswordKey: 

extraMounts:
  enabled: true
  mounts:
  - name: varlogpods
    path: /var/logs/pods

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi




