# Basic info
secretsRef: "__REQUIRED__"
image:
  repository: fluent/fluentd-kubernetes-daemonset
  tag: elasticsearch
  pullPolicy: Always

# elasticScheme http or https
elasticScheme: http

# elasticSearch host
elasticSearchHost: elastic

# elasticSearch port
elasticSearchPort: 9200  

# elasticUsername
fluentDUsername: fluentd

# password keys
xpackSettings: 

extraMounts:
  enabled: false
  # mounts:
  # - name: varlogpods
  #   path: /var/logs/pods

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi




