apiVersion: v1
name: traefik
version: 1.3.0
appVersion: 1.2.1
description: A Traefik based Kubernetes ingress controller with Let's Encrypt support and Landscaper support
keywords:
- traefik
- ingress
- acme
- letsencrypt
home: http://traefik.io/

