{{- if .Values.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-default-cert
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  tls.crt: 
    valueFrom:
      secretKeyRef:
        name: {{ .Values.secretsRef | quote }}
        key:  {{ .Values.certDataKey }}
  tls.key: 
    valueFrom:
      secretKeyRef:
        name: {{ .Values.secretsRef | quote }}
        key:  {{ .Values.certKeyKey }}
{{- end }}
