apiVersion: extensions/v1beta1
kind: Ingress
metadata:
   name:  {{ template "fullname" . }}
   {{ if .Values.stripPrefixEnabled }}
   annotations:
    traefik.frontend.rule.type: PathPrefixStrip
   {{ end }} 
spec:
  rules:
  - http:
      paths:
      {{- range .Values.rules }}
      - path: {{ .path }}
        backend:
          serviceName: {{ .serviceName }}
          servicePort: {{ .servicePort }}
      {{- end }}

