# Basic info
replicaCount: "__REQUIRED__"
secretsRef: "__REQUIRED__"
image:
  repository: registry.hub.docker.com/datamountaineer/kafka-connect-yahoo-source
  tag: 0.3.0.1
  pullPolicy: IfNotPresent

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi
javaHeap: 256M

# Monitoring
monitoring:
  pipeline: "__REQUIRED__"
  enabled: true
  port: 9102
  path: "/metrics"

# SSL/TLS options can be enabled, some connectors provide SSL support, others the newer TLS
# Set the corresponding value type to true. For SSL persistent volumes or hostPaths will be
# mounted under /connector-extra-config. Set the connectors ssl/tls option paths to be use this
# TLS is done via Secrets, create a secret for containing the certificates (base64 encoded) and
# create a secret for them, adding the name of the secret to the `secretsRef` other wise if using
# Eneco's Landscaper it will do this for you.

# SSL mount path on hosts, should be the base path of any ssl keystore/truststore paths
ssl:
  enabled: false
  # Path to the directory on the hosts
  path: /ssl

  # If persistent volumes should be used for ssl keystore/truststore paths
  persistentVolumes:
    enable: false
    existingClaim:

# TLS, for those connectors supporting TLS certificates rather than ssl key/truststores
# contents for mount take from config map
tls:
  enabled: false

## Avro schemas, for those connectors, MQTT and JMS source that support Avro converters we
## need the schemas, so we'll mount as a ConfigMap. Set the key value pairs, filename and data
## matching the value option avroSchema. Key is the file name, value is the avro schema contents
#avroSchemaFiles:
#  schema_file_name:  ""

applicationId: "__REQUIRED__"
topics: "__REQUIRED__"
tasksMax: 3


connectorClass: com.datamountaineer.streamreactor.connect.yahoo.source.YahooSourceConnector
# sourceStocksSubscriptions Sets the financial's stocks to query from Yahoo finance. type: STRING importance: HIGH
sourceStocksSubscriptions: "__REQUIRED__"

# sourceFxSubscriptions Sets the foreign exchange values to retrieve from Yahoo finance type: STRING importance: HIGH
sourceFxSubscriptions: "__REQUIRED__"

# sourceBufferSize How many records it should buffer as it gets more data from yahoo type: INT importance: MEDIUM
sourceBufferSize: 10000

# sourceStocksTopic Specifies which kafka topic will receive the the stock information type: STRING importance: HIGH
sourceStocksTopic: "__REQUIRED__"

# sourceFxTopic Specifies the target kafka topic to send the FX values to type: STRING importance: HIGH
sourceFxTopic: "__REQUIRED__"

# sourceErrorPolicy Sets the error handling approach. Available options are THROW and NOOP type: STRING importance: HIGH
sourceErrorPolicy: THROW

# sourcePollInterval Specifies how often if polls Yahoo services for new data type: LONG importance: HIGH
sourcePollInterval: 60000

# sourceRetries  type: INT importance: MEDIUM
sourceRetries: 10

