{{- if or .Values.kafka.ssl.enabled .Values.kafka.sasl.enabled }} 

kind: Secret
metadata:
  name: {{ include "fullname" . }}
  labels:
    app: {{ include "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    lenses: lenses-secret
data:
  {{- if .Values.kafka.ssl.enabled }}
  client.truststore.jks: {{ .Values.kafka.ssl.trustStoreFileData }}
  client.keystore.jks: {{ .Values.kafka.ssl.keyStoreFileData }}
  {{- end }}
  {{- if .Values.kafka.sasl.enabled }}
  keytab:  {{ .Values.kafka.sasl.keyTabData }}
  {{- end }}
stringData:
  {{- if .Values.kafka.sasl.enabled }}
  jaas.conf: |-
{{ .Values.kafka.sasl.jaasFileData | default "" | indent 4 }}
  {{- end }}
  {{- if or .Values.kafka.ssl.enabled .Values.kafka.sasl.enabled}}  
  extras: |-
{{ include "extras" . | indent 4 }}
  {{- end -}}  
{{- end -}}
