apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        hostPort: {{ .Values.rest.restPort | quote }}
        containerPort: {{ .Values.rest.restPort | quote }}
        pipeline: {{ .Values.monitoring.pipeline | quote }}
      annotations:
        prometheus.io/scrape: {{ .Values.monitoring.enabled | quote }}
        prometheus.io/port: {{ .Values.monitoring.jmxPort | quote }}
        prometheus.io/path: {{ .Values.monitoring.path | quote }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.rest.restPort }}
          name: connect-rest
        - containerPort: {{ .Values.monitoring.jmxPort }}
          name: connect-jmx
        livenessProbe:
          httpGet:
            path: /topics
            port: {{ .Values.rest.restPort }}
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: KAFKA_REST_ZOOKEEPER_CONNECT 
          value: {{ .Values.rest.zookeeperConnect | quote }}
        - name: KAFKA_REST_SCHEMA_REGISTRY_URL
          value: {{ .Values.rest.schemaRegistryUrl | quote }}
        - name: KAFKA_REST_LISTENERS
          value: {{ .Values.rest.listeners | quote }}
        - name: KAFKA_REST_DEBUG
          value: {{ .Values.rest.debug | quote }} 
        - name: KAFKA_REST_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
